#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

IFS=$'\n'
PACKAGE_LOCK_REGEX="(^packages\/.*\/package-lock\.json)|(^package-lock\.json)"
PACKAGES=("$(git diff --name-only HEAD@{1} HEAD | grep -E "$PACKAGE_LOCK_REGEX")")

if [[ ${PACKAGES[@]} ]]; then
  for package in $PACKAGES; do
    echo "📦 $package was changed. Running npm install to update your dependencies..."
    DIR=$(dirname package)
    cd "$DIR" && npm install
  done
else
  echo "📦 No package-lock.json files were changed. Skipping npm install..."
  DIR=$(dirname package)
  cd "$DIR" && npm run build
fi
